codeco33/aihometraining

teamproject/src/main/resources/templates/challenge/challengeConfig/challengeConfigList.html
=> [team] challengeConfigList 수정

teamproject/src/main/resources/templates/main.html
=> [team] main화면코드바꿈

teamproject/src/main/java/aihometraining/team/controller/MainController.java
=> [team] 메인화면위치 서로 바꿈

teamproject/src/main/resources/templates/payment/mypaymentList.html, teamproject/src/main/resources/templates/payment/paymentList.html, teamproject/src/main/resources/templates/point/mypointList.html, teamproject/src/main/resources/templates/point/pointList.html, teamproject/src/main/resources/templates/refund/myrefundList.html, teamproject/src/main/resources/templates/refund/refundList.html
=> Jsg 결제,환불,포인트 폴더 및 파일 생성

teamproject/src/main/resources/templates/userfragments/header.html
=> [team] 로고 경로 변경

teamproject/src/main/java/aihometraining/team/challengeConfig/controller/ChallengeConfigController.java, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeCategoryInsert.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeCategoryUpdate.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeList.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeListDetail.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeListIng.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengePoint.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeReportDetail.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeReportList.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeSettingInsert.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeSettingUpdate.html, teamproject/src/main/resources/templates/challenge/challengeEnter/challengeEnterDetail.html, teamproject/src/main/resources/templates/challenge/challengeEnter/challengeEnterList.html, teamproject/src/main/resources/templates/challenge/challengeEnter/challengeEnterPaymemt.html, teamproject/src/main/resources/templates/challenge/challengeEnter/challengePlanDoInsert.html, teamproject/src/main/resources/templates/challenge/challengeGather/challengeGaterInMember.html, teamproject/src/main/resources/templates/challenge/challengeGather/challengeGaterInMemberDetail.html, teamproject/src/main/resources/templates/challenge/challengeGather/challengeGatherAdmin.html, teamproject/src/main/resources/templates/challenge/challengeGather/challengeGatherAdminDetail.html, teamproject/src/main/resources/templates/challenge/challengeGather/challengeGatherInsert.html, teamproject/src/main/resources/templates/challenge/challengeGather/challengeGatherList.html, teamproject/src/main/resources/templates/challenge/challengeGather/challengeGatherListDetail.html, teamproject/src/main/resources/templates/challenge/challengeGather/challengeGatherUpdate.html, teamproject/src/main/resources/templates/fragments/leftmenu.html
[team]challengeConfig경로를 leftmenu에 연결
=> [team]challengeConfig경로를 left메뉴에 연결

teamproject/src/main/resources/templates/member/memberList.html
Detail : LMS Test memberList.html 220318
=> [team] memberList.html

teamproject/src/main/java/aihometraining/team/controller/PaymentController.java, teamproject/src/main/java/aihometraining/team/controller/PointController.java, teamproject/src/main/java/aihometraining/team/controller/RefundController.java, teamproject/src/main/resources/templates/fragments/leftmenu.html, teamproject/src/main/resources/templates/payment/paymentList.html, teamproject/src/main/resources/templates/point/givePoint.html, teamproject/src/main/resources/templates/point/pointStandard.html
=> Jsg leftmenu 수정/controller 및 페이지 생성/ 결제 내역 페이지 수정

teamproject/src/main/resources/templates/challenge/challengeConfig/challengeCategoryInsert.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeCategoryUpdate.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeConfigList.html, teamproject/src/main/resources/templates/fragments/contentsHeader.html
=> [team]contentsHeader 띄어쓰기

teamproject/src/main/java/aihometraining/team/controller/EClassController.java, teamproject/src/main/java/aihometraining/team/controller/MainController.java, teamproject/src/main/java/aihometraining/team/controller/ReportController.java, teamproject/src/main/resources/templates/eClass/eClassConfig/eClassCategoryDelete.html, teamproject/src/main/resources/templates/eClass/eClassConfig/eClassCategoryInsert.html, teamproject/src/main/resources/templates/eClass/eClassConfig/eClassCategoryList.html, teamproject/src/main/resources/templates/eClass/eClassConfig/eClassCategoryUpdate.html, teamproject/src/main/resources/templates/eClass/eClassConfig/eClassConfigMain.html, teamproject/src/main/resources/templates/fragments/leftmenu.html, teamproject/src/main/resources/templates/login/loginList.html, teamproject/src/main/resources/templates/report/myReportList.html, teamproject/src/main/resources/templates/report/reportList.html, teamproject/src/main/resources/templates/report/reportStandardList.html
DETAIL : 운동 카테고리 관리 및 신고 관리 경로 설정
=> [team] 운동 카테고리, 로그인, 신고 폴더 생성

teamproject/src/main/resources/templates/fragments/leftmenu.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutLogConfigMain.html
=> [team] 카테고리 아이콘 변경

teamproject/src/main/java/aihometraining/team/eclassController/eClassController.java, teamproject/src/main/java/aihometraining/team/eclassService/eClassService.java, teamproject/src/main/resources/templates/eClass/eclassApprovedList.html, teamproject/src/main/resources/templates/userfragments/header.html
=> [KJH]개설된 운동리스트 페이지 연결

teamproject/src/main/java/aihometraining/team/controller/PaymentController.java, teamproject/src/main/resources/static/asset/css/style.css, teamproject/src/main/resources/templates/payment/paymentList.html
=> Jsg 관리자 페이지 css 수정

teamproject/src/main/java/aihometraining/team/controller/MainController.java, teamproject/src/main/java/aihometraining/team/eclassController/eClassController.java, teamproject/src/main/resources/templates/member/wishList.html, teamproject/src/main/resources/templates/payment/payment.html, teamproject/src/main/resources/templates/userfragments/header.html
=> [team] 메인 header 경로 수정

teamproject/src/main/java/aihometraining/team/challengeGather/controller/ChallengeGaterController.java, teamproject/src/main/resources/templates/challenge/challengeGather/challengeGatherList.html, teamproject/src/main/resources/templates/userfragments/header.html, teamproject/src/main/resources/templates/userfragments/preloader.html, teamproject/src/main/resources/templates/userfragments/userJavaScripts.html
userjavaScripts th구문으로 변경, preloder th구문으로 변경, header에 challenge연결
=> [team] 공통파일 수정

teamproject/src/main/java/aihometraining/team/challengeConfig/controller/ChallengeConfigController.java, teamproject/src/main/java/aihometraining/team/challengeConfig/dto/challengeCategory.java, teamproject/src/main/java/aihometraining/team/challengeConfig/mapper/ChallengeConfigMapper.java, teamproject/src/main/java/aihometraining/team/challengeConfig/service/ChallengeConfigService.java, teamproject/src/main/java/aihometraining/team/dto/ChallengeCategory.java, teamproject/src/main/java/aihometraining/team/dto/Member.java, teamproject/src/main/resources/mapper/ChallengeConfigMapper.xml, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeCategoryInsert.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeConfigList.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeList.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeSettingInsert.html, teamproject/src/main/resources/templates/challenge/challengeGather/challengeGatherList.html
[CBR] db값 가져오기 
dto만듦, Member꺼도 만들었으니 나중에 수정해서 써주세요
mapper폴더 만들었습니다.
=> [CBR] db값 가져오기 

teamproject/src/main/resources/static/assets/css/style.css, teamproject/src/main/resources/templates/challenge/challengeGather/challengeGatherList.html, teamproject/src/test/java/aihometraining/team/TeamprojectApplicationTests.java
=> [CBR] css 추가

teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutAIVideoList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutCategoryList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutLogConfigMain.html
=> [team] 일지 수정

teamproject/src/main/java/aihometraining/team/workoutLogConfig/controller/WorkoutLogConfigController.java, teamproject/src/main/resources/templates/userfragments/header.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutAIVideoDelete.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutAIVideoList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutAIVideoUpdate.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutCategoryDelete.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutCategoryInsert.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutCategoryList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutCategoryUpdate.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutLogConfigMain.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutGoalPlanList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutLogList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutLogMain.html
[team] userfragments-header : 화면 연결
=> [team] userfragments-header : 화면 연결

teamproject/src/main/java/aihometraining/team/workoutLogUser/controller/WorkoutLogUserController.java, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutGoalPlanList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutLogList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutLogMain.html
=> [team] workoutuser 폴더 수정

teamproject/src/main/resources/templates/member/addMember.html, teamproject/src/main/resources/templates/member/login.html, teamproject/src/main/resources/templates/member/mypage.html
DETAIL : 로그인 및 회원 가입 화면 구성했음
레이아웃 없애고 로그인, 회원 가입 화면으로 redirect 이동시킬 예정
=> [team] LMS 로그인, 회원 가입 화면 구성

teamproject/src/main/resources/templates/member/wishList.html, teamproject/src/main/resources/templates/userfragments/header.html
=> [team] 배포전 수정

teamproject/src/main/resources/templates/challenge/challengeConfig/challengeConfigList.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeListIng.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengePoint.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutAIVideoList.html
=> [team] table js 이름 변경

teamproject/src/main/java/aihometraining/team/challengeGather/controller/ChallengeGaterController.java, teamproject/src/main/resources/templates/userfragments/slider.html
slider에 title, headerList가져오게 변경
=> [team] CBR 

teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutGoalPlanList.html
=> [team] workoutgoalplanList 수정

teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutGoalPlanList.html
=> [team] workoutloggoalplanList

teamproject/src/main/java/aihometraining/team/challenge/controller/ChallengeGaterController.java, teamproject/src/main/java/aihometraining/team/challenge/mapper/ChallengeGatherMapper.java, teamproject/src/main/java/aihometraining/team/challenge/service/ChallengeGatherService.java, teamproject/src/main/java/aihometraining/team/dto/ChallengeGather.java, teamproject/src/main/resources/mapper/ChallengeGatherMapper.xml, teamproject/src/main/resources/templates/challenge/challengeGather/challengeGatherList.html
[CBR] challlengeGatherList db랑 연동작업
challlengeGatherController 수정
challlengeGatherService 생성
challlengeGatherMapper생성
challlengeGatherMapper.xml 쿼리문 작성
=> [CBR] challlengeGatherList db랑 연동작업

teamproject/src/main/resources/templates/challenge/challengeGather/challengeGatherList.html, teamproject/src/main/resources/templates/layout/userdefault.html
[CBR]userdefault 에서 customContects블럭 위치 조정함
=> [team]userdefault 에서 customContects블럭 위치 조정함

teamproject/src/main/java/aihometraining/team/controller/MemberController.java, teamproject/src/main/resources/mapper/MemberMapper.xml, teamproject/src/main/resources/templates/member/addInfo.html, teamproject/src/main/resources/templates/member/memberDetail.html, teamproject/src/main/resources/templates/member/memberList.html
DETAIL : 220324 memberList 기능 구현 진행중
=> [LMS] MemberMapper.xml 작업 진행중

teamproject/src/main/java/aihometraining/team/challenge/controller/ChallengeGaterController.java, teamproject/src/main/resources/templates/layout/userdefault.html, teamproject/src/main/resources/templates/userfragments/head.html, teamproject/src/main/resources/templates/userfragments/userJavaScripts.html
[team] cbr 자바스크립트 커스텀 가능하도록 수정
=> [team] cbr 자바스크립트 커스텀 가능하도록 수정

teamproject/src/main/resources/templates/challenge/challengeGather/challengeGatherInsert.html
[CBR] challengeGatherInsert 화면구현
=> [CBR] challengeGatherInsert 화면구현

teamproject/src/main/java/aihometraining/team/challenge/controller/ChallengeEnterController.java, teamproject/src/main/resources/templates/challenge/challengeEnter/challengeEnterList.html
[CBR] challengeEnterList 화면 구현
=> [CBR] challengeEnterList 화면 구현

teamproject/src/main/java/aihometraining/team/challenge/controller/ChallengeEnterController.java, teamproject/src/main/resources/templates/userfragments/header.html
[CBR] header와 challengeEnterList연결
=> [CBR] header와 challengeEnterList연결

teamproject/src/main/resources/templates/challenge/challengeEnter/challengeEnterDetail.html, teamproject/src/main/resources/templates/challenge/challengeEnter/challengeEnterList.html, teamproject/src/main/resources/templates/challenge/challengeEnter/challengePlanDoInsert.html
[CBR] challengeEnterList와 challengePlanDoInsert화면 구현,
challengeEnterDetail연결
=> [CBR] challengeEnterList와 challengePlanDoInsert화면 구현,

teamproject/src/main/java/aihometraining/team/controller/MainController.java, teamproject/src/main/resources/static/asset/js/main.js, teamproject/src/main/resources/templates/adminmain.html, teamproject/src/main/resources/templates/fragments/leftmenu.html, teamproject/src/main/resources/templates/payment/paymentList.html
=> [team] 관리자 페이지 

teamproject/src/main/java/aihometraining/team/workoutLog/controller/WorkoutLogUserController.java, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutAIVideoInsert.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutGoalInsert.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutGoalList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutLogBest.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutLogList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutLogMain.html
=> [CMH] workoutLog 화면 구현

teamproject/src/main/resources/templates/member/memberList.html
=> [LMS] 회원 목록 화면 작업

teamproject/src/main/java/aihometraining/team/controller/MemberController.java
DETAIL : MemberController 경로 작업
=> [LMS] 회원 권한 목록 조회 화면 작업

teamproject/src/main/resources/static/assets/css/style.css, teamproject/src/main/resources/templates/userfragments/footer.html, teamproject/src/main/resources/templates/userfragments/head.html
=> [이영호]메인화면 필요 아이콘 및 해당 소스 변경

teamproject/src/main/resources/templates/member/memberList.html
DETAIL : 220328 memberList DB의 회원 목록 가져오기
=> [LMS] 회원 목록 작업

teamproject/src/main/java/aihometraining/team/controller/MemberController.java, teamproject/src/main/java/aihometraining/team/dto/MemberLevel.java, teamproject/src/main/resources/mapper/MemberMapper.xml, teamproject/src/main/resources/templates/member/memberLevelList.html, teamproject/src/main/resources/templates/member/memberList.html
DETAIL : 220328 회원 권한 목록 화면 처리 작업
=> [LMS] 회원 권한 목록 화면 처리 작업

teamproject/src/main/java/aihometraining/team/diet/controller/DietController.java, teamproject/src/main/java/aihometraining/team/diet/mapper/DietMapper.java, teamproject/src/main/java/aihometraining/team/diet/service/DietService.java, teamproject/src/main/resources/templates/diet/dietBankList.html, teamproject/src/main/resources/templates/userfragments/header.html
1. 메인 메뉴 식단 은행 페이지 링크 
2. 컨트롤러 업데이트
=> [이영호] 식단은행 펭이지 / 컨트롤러 추가

teamproject/src/main/java/aihometraining/team/diet/controller/DietController.java, teamproject/src/main/resources/templates/diet/dietBankList.html, teamproject/src/main/resources/templates/diet/dietBankListAdmin.html, teamproject/src/main/resources/templates/fragments/leftmenu.html
=> [이영호] admin페이지 leftmenu 작업 >> 식단은행 페이지 링크연결

teamproject/src/main/java/aihometraining/team/dto/EClassCategoryLarge.java, teamproject/src/main/java/aihometraining/team/dto/EClassCategoryMedium.java, teamproject/src/main/java/aihometraining/team/dto/EClassCategorySmall.java
DETAIL : 220328 운동 클래스 카테고리 대, 중, 소 dto 작업
=> [LMS] 운동 클래스 카테고리 대, 중, 소 dto 작업

teamproject/src/main/java/aihometraining/team/dto/WorkoutGoal.java, teamproject/src/main/java/aihometraining/team/workoutLog/controller/WorkoutLogUserController.java, teamproject/src/main/java/aihometraining/team/workoutLog/mapper/WorkoutLogUserMapper.java, teamproject/src/main/java/aihometraining/team/workoutLog/service/WorkoutLogUserService.java, teamproject/src/main/resources/mapper/WorkoutLogUserMapper.xml, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutAIVideoInsert.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutAIVideoList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutCategoryInsert.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutCategoryList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutLogConfigMain.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutGoalInsert.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutGoalList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutLogInsert.html
[CMH] workoutLog admin/user 페이지 구현 작업 진행 중
workoutGoalList 데이터베이스 연결
=> [CMH] workoutLog admin/user 페이지 구현 작업 진행 중

teamproject/src/main/java/aihometraining/team/controller/RefundController.java, teamproject/src/main/resources/templates/point/givePoint.html, teamproject/src/main/resources/templates/point/pointList.html, teamproject/src/main/resources/templates/point/pointStandard.html, teamproject/src/main/resources/templates/refund/refundDetail.html, teamproject/src/main/resources/templates/refund/refundList.html, teamproject/src/main/resources/templates/refund/refundStandard.html
환불 기준 관리
포인트 지급 
포인트 내역
포인트 지급 기준
=> Jsg 관리자페이지 환면 구현

teamproject/src/main/java/aihometraining/team/challenge/controller/ChallengeConfigController.java, teamproject/src/main/java/aihometraining/team/challenge/controller/ChallengeGaterController.java, teamproject/src/main/java/aihometraining/team/challenge/mapper/ChallengeConfigMapper.java, teamproject/src/main/java/aihometraining/team/challenge/service/ChallengeConfigService.java, teamproject/src/main/resources/mapper/ChallengeConfigMapper.xml, teamproject/src/main/resources/mapper/ChallengeGatherMapper.xml, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeCategoryInsert.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeCategoryInsertFormwizard.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeCategoryUpdate.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeConfigList.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeList.html, teamproject/src/main/resources/templates/challenge/challengeConfig/challengeSettingInsert.html, teamproject/src/main/resources/templates/challenge/challengeConfig/datepickerEx.html, teamproject/src/main/resources/templates/fragments/challengeleftmenu.html
=> [CBR] 화면구현

teamproject/src/main/java/aihometraining/team/controller/EClassCategoryController.java, teamproject/src/main/java/aihometraining/team/dto/EClassCategoryLarge.java, teamproject/src/main/java/aihometraining/team/mapper/EClassCategoryMapper.java, teamproject/src/main/java/aihometraining/team/service/EClassCategoryService.java, teamproject/src/main/resources/mapper/EClassCategoryMapper.xml, teamproject/src/main/resources/templates/eClass/eClassConfig/eClassCategoryList.html
DETAIL : 220329 운동 클래스 카테고리 목록 조회 작업
=> [LMS] 운동 클래스 카테고리 목록 조회 작업

teamproject/src/main/java/aihometraining/team/controller/EClassCategoryController.java, teamproject/src/main/resources/templates/eClass/eClassConfig/eClassCategoryInsert.html, teamproject/src/main/resources/templates/eClass/eClassConfig/eClassCategoryList.html
DETAIL : 220329 운동 클래스 카테고리 등록 폼 작업
=> [LMS] 운동 클래스 카테고리 등록 폼 작업

teamproject/src/main/resources/templates/refund/myrefundList.html
=> JSG 선택회원 환불 내역

teamproject/src/main/java/aihometraining/team/eclassController/eClassController.java, teamproject/src/main/resources/templates/eClass/myEClassApplyList.html, teamproject/src/main/resources/templates/eClass/myeClassList.html, teamproject/src/main/resources/templates/fragments/eclassleftmenu.html
eClassadmin 운동클래스 리스트 추가
leftmenu 수정
=> [KJH] eClassadmin 운동클래스 신청현황 추가

teamproject/src/main/java/aihometraining/team/controller/MemberController.java, teamproject/src/main/java/aihometraining/team/controller/ReportController.java, teamproject/src/main/java/aihometraining/team/dto/Report.java, teamproject/src/main/java/aihometraining/team/dto/ReportStandard.java, teamproject/src/main/java/aihometraining/team/mapper/ReportMapper.java, teamproject/src/main/java/aihometraining/team/service/MemberService.java, teamproject/src/main/java/aihometraining/team/service/ReportService.java, teamproject/src/main/resources/mapper/ReportMapper.xml, teamproject/src/main/resources/templates/report/modifyReportStandardList.html, teamproject/src/main/resources/templates/report/removeReportStandardList.html, teamproject/src/main/resources/templates/report/reportStandardList.html
DETAIL : 220401 신고 기준 목록 조회 작업 DB연결 성공
=> [LMS] 신고 기준 목록 조회 작업

teamproject/src/main/java/aihometraining/team/controller/MypageController.java, teamproject/src/main/java/aihometraining/team/controller/PaymentController.java, teamproject/src/main/resources/templates/fragments/header.html, teamproject/src/main/resources/templates/fragments/mypageleftmenu.html, teamproject/src/main/resources/templates/member/mypage.html, teamproject/src/main/resources/templates/member/wishList.html, teamproject/src/main/resources/templates/payment/mypaymentList.html, teamproject/src/main/resources/templates/point/mypointList.html, teamproject/src/main/resources/templates/refund/myrefundList.html
left-menu 경로수정
마이페이지 결제내역,환불내역,포인트 등 수정
=> Jsg 마이페이지 수정

teamproject/src/main/java/aihometraining/team/controller/ReportController.java, teamproject/src/main/java/aihometraining/team/dto/Report.java, teamproject/src/main/java/aihometraining/team/service/ReportService.java, teamproject/src/main/resources/mapper/ReportMapper.xml, teamproject/src/main/resources/templates/report/reportList.html
DETAIL :
220401
report 신고 테이블 생성
Report DTO 작업
Report Controller, Service, Mapper 작업
=> [LMS] 신고 목록 조회 구현 작업

teamproject/src/main/resources/templates/userfragments/header.html
DETAIL : 220401 로그인 시 로그인, 회원가입 메뉴 안나오도록 작업
=> [LMS] 로그인 시 로그인, 회원가입 메뉴 안나오도록 작업

teamproject/src/main/java/aihometraining/team/controller/MypageController.java, teamproject/src/main/java/aihometraining/team/controller/PaymentController.java, teamproject/src/main/java/aihometraining/team/controller/RefundController.java, teamproject/src/main/resources/templates/payment/mypaymentList.html, teamproject/src/main/resources/templates/payment/paymentDetail.html, teamproject/src/main/resources/templates/refund/myrefundList.html, teamproject/src/main/resources/templates/refund/refundList.html
-거래내역
-환불내역
-상세페이지
-daterangepicker
=> Jsg 마이페이지 UI 및 경로 수정

teamproject/src/main/java/aihometraining/team/controller/PaymentController.java, teamproject/src/main/resources/templates/eClass/eClassTake.html, teamproject/src/main/resources/templates/fragments/mypageleftmenu.html, teamproject/src/main/resources/templates/member/wishList.html, teamproject/src/main/resources/templates/point/mypointList.html, teamproject/src/main/resources/templates/refund/myrefundList.html
[마이페이지 포인트 UI 완성]
[마이페이지 left-menu 수정]
[수강신청/결제 페이지 경로 및 UI수정]
=> Jsg 220403

teamproject/src/main/java/aihometraining/team/dto/WorkoutLog.java, teamproject/src/main/java/aihometraining/team/dto/WorkoutLogPrivacybounds.java, teamproject/src/main/java/aihometraining/team/workoutLog/controller/WorkoutLogConfigController.java, teamproject/src/main/java/aihometraining/team/workoutLog/controller/WorkoutLogUserController.java, teamproject/src/main/java/aihometraining/team/workoutLog/mapper/WorkoutLogConfigMapper.java, teamproject/src/main/java/aihometraining/team/workoutLog/mapper/WorkoutLogUserMapper.java, teamproject/src/main/java/aihometraining/team/workoutLog/service/WorkoutLogConfigService.java, teamproject/src/main/java/aihometraining/team/workoutLog/service/WorkoutLogUserService.java, teamproject/src/main/resources/mapper/WorkoutLogConfigMapper.xml, teamproject/src/main/resources/mapper/WorkoutLogUserMapper.xml, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutLogConfigMain.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutLogInsert.html
=> [CMH] 일지 등록 - DB 연결

teamproject/src/main/java/aihometraining/team/controller/MypageController.java, teamproject/src/main/java/aihometraining/team/controller/PaymentController.java, teamproject/src/main/resources/templates/eClass/eClassTake.html, teamproject/src/main/resources/templates/payment/payment.html, teamproject/src/main/resources/templates/payment/paymentDetail.html
[JSG 결제상세페이지 thymeleaf layout 마이페이지/관리자페이지 조건처리]
[JSG 수강신청페이지 UI 완성]
[JSG 결제페이지 UI 수정]
=> Jsg 결제내역상세페이지/수강신청페이지/결제페이지 UI 

teamproject/src/main/java/aihometraining/team/eclassController/eClassController.java, teamproject/src/main/resources/mapper/EClassMapper.xml, teamproject/src/main/resources/static/assets/js/eClassNav.js, teamproject/src/main/resources/templates/eClass/eClassOpenApplyFormUpdate.html
=> [KJH]2022-04-04

teamproject/src/main/java/aihometraining/team/config/WebConfig.java, teamproject/src/main/java/aihometraining/team/controller/MainController.java, teamproject/src/main/java/aihometraining/team/controller/MemberController.java, teamproject/src/main/java/aihometraining/team/interceptor/CommonInterceptor.java, teamproject/src/main/java/aihometraining/team/interceptor/LoginInterceptor.java, teamproject/src/main/resources/mapper/MemberMapper.xml, teamproject/src/main/resources/templates/main.html, teamproject/src/main/resources/templates/member/mypage.html, teamproject/src/main/resources/templates/userfragments/header.html
DETAIL : 220405 interceptor 작업 
관리자 인증 관리자 페이지 이동하도록 작업
로그인 시 로그인 회원 이름 출력 작업
=> [LMS] 관리자 회원 로그인 시 관리자 페이지 이동 구현

teamproject/src/main/java/aihometraining/team/workoutLog/controller/WorkoutLogUserController.java, teamproject/src/main/java/aihometraining/team/workoutLog/mapper/WorkoutLogUserMapper.java, teamproject/src/main/java/aihometraining/team/workoutLog/service/WorkoutLogUserService.java, teamproject/src/main/resources/mapper/WorkoutLogConfigMapper.xml, teamproject/src/main/resources/mapper/WorkoutLogUserMapper.xml, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutLogInsert.html
[CMH] 일지 등록 시 카테고리 대-중-소 분류 후 등록
=> [CMH] 일지 등록 시 카테고리 대-중-소 분류 후 등록

teamproject/src/main/java/aihometraining/team/controller/EClassCategoryController.java, teamproject/src/main/java/aihometraining/team/controller/MainController.java, teamproject/src/main/java/aihometraining/team/interceptor/LoginInterceptor.java, teamproject/src/main/resources/templates/userfragments/header.html
DETAIL : 220405
MainController 작업
관리자 페이지 uri에 /admin 패턴이 없기 때문에 다른 Controller도 작업 후 다시 interceptor 작업할 예정
=> [LMS] 관리자 페이지는 관리자만 들어가도록 작업

teamproject/src/main/java/aihometraining/team/workoutLog/controller/WorkoutLogConfigController.java, teamproject/src/main/java/aihometraining/team/workoutLog/mapper/WorkoutLogConfigMapper.java, teamproject/src/main/resources/mapper/WorkoutLogConfigMapper.xml, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutAIVideoList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutCategoryInsert.html, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutCategoryList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutLogInsert.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutLogUpdate.html
=> [CMH] 에이작스 및 경로 변경

teamproject/src/main/java/aihometraining/team/config/WebConfig.java
DETAIL : 220405 WebConfig 수정
.excludePathPatterns("/fullcalendar/**")
=> [LMS] WebConfig 수정

teamproject/src/main/java/aihometraining/team/controller/MainController.java, teamproject/src/main/java/aihometraining/team/controller/MypageController.java, teamproject/src/main/java/aihometraining/team/controller/PaymentController.java, teamproject/src/main/java/aihometraining/team/controller/RefundController.java, teamproject/src/main/resources/templates/eClass/eClassTake.html, teamproject/src/main/resources/templates/eClass/mySignUpForClassList.html, teamproject/src/main/resources/templates/eClass/myeClassList.html, teamproject/src/main/resources/templates/fragments/leftmenu.html, teamproject/src/main/resources/templates/fragments/mypageleftmenu.html, teamproject/src/main/resources/templates/payment/mypaymentList.html, teamproject/src/main/resources/templates/payment/paymentDetail.html, teamproject/src/main/resources/templates/payment/paymentList.html, teamproject/src/main/resources/templates/refund/refundDetail.html, teamproject/src/main/resources/templates/refund/refundList.html
[JSG 환불신청 모달 UI 완성]
[JSG 수강신청 폼 method 수정]
[[team] JSG 마이페이지/관리자 페이지 경로 수정]
[[team] JSG 마이페이지 운동클래스 관리 경로 등 수정]
=> Jsg 마이페이지 경로 및 controller 수정

teamproject/src/main/java/aihometraining/team/eclassController/eClassController.java, teamproject/src/main/resources/templates/eClass/studentList.html, teamproject/src/main/resources/templates/fragments/eclassleftmenu.html
=> [team] JSG 운동클래스 관리자 페이지 경로 수정/ 왼쪽메뉴 수정

teamproject/src/main/java/aihometraining/team/config/WebConfig.java, teamproject/src/main/java/aihometraining/team/controller/MemberController.java, teamproject/src/main/java/aihometraining/team/interceptor/LoginInterceptor.java, teamproject/src/main/java/aihometraining/team/service/MemberService.java, teamproject/src/main/resources/mapper/MemberMapper.xml, teamproject/src/main/resources/templates/member/addMember.html, teamproject/src/main/resources/templates/member/login.html, teamproject/src/main/resources/templates/userfragments/header.html
DETAIL : 220407
회원 가입 처리 및 로그인 처리 수정
MemberController /admin 작업
=> [LMS] 회원 가입 처리 및 로그인 처리 수정

teamproject/src/main/java/aihometraining/team/dto/WorkoutLog.java, teamproject/src/main/java/aihometraining/team/dto/WorkoutLogLike.java, teamproject/src/main/java/aihometraining/team/workoutLog/controller/WorkoutLogConfigController.java, teamproject/src/main/java/aihometraining/team/workoutLog/controller/WorkoutLogUserController.java, teamproject/src/main/java/aihometraining/team/workoutLog/mapper/WorkoutLogConfigMapper.java, teamproject/src/main/java/aihometraining/team/workoutLog/mapper/WorkoutLogUserMapper.java, teamproject/src/main/java/aihometraining/team/workoutLog/service/WorkoutLogConfigService.java, teamproject/src/main/java/aihometraining/team/workoutLog/service/WorkoutLogUserService.java, teamproject/src/main/resources/mapper/CommonMapper.xml, teamproject/src/main/resources/mapper/WorkoutLogConfigMapper.xml, teamproject/src/main/resources/mapper/WorkoutLogUserMapper.xml, teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutLogConfigMain.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutLogList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutLogMain.html
=> [CMH] 기능 구현 중

teamproject/src/main/java/aihometraining/team/config/WebConfig.java, teamproject/src/main/java/aihometraining/team/controller/EClassCategoryController.java, teamproject/src/main/java/aihometraining/team/controller/MainController.java, teamproject/src/main/java/aihometraining/team/controller/MemberAdminController.java, teamproject/src/main/java/aihometraining/team/controller/MemberController.java, teamproject/src/main/java/aihometraining/team/controller/ReportController.java, teamproject/src/main/java/aihometraining/team/interceptor/CommonInterceptor.java, teamproject/src/main/java/aihometraining/team/interceptor/LoginInterceptor.java, teamproject/src/main/resources/templates/fragments/leftmenu.html, teamproject/src/main/resources/templates/member/addInfo.html, teamproject/src/main/resources/templates/member/addMember.html, teamproject/src/main/resources/templates/member/login.html, teamproject/src/main/resources/templates/userfragments/header.html
DETAIL : 220412 
경로 수정 및 권한에 따라 페이지 경로 접근 막는 작업 진행
=> [LMS] 경로 수정 및 권한에 따라 페이지 경로 접근 막는 작업 진행

teamproject/src/main/java/aihometraining/team/interceptor/LoginInterceptor.java, teamproject/src/main/resources/templates/fragments/header.html, teamproject/src/main/resources/templates/userfragments/header.html
DETAIL : 220412 관리자 페이지 header 작업
=> [LMS] 관리자 페이지 header 작업

teamproject/src/main/java/aihometraining/team/controller/PaymentController.java, teamproject/src/main/java/aihometraining/team/dto/EClassApproved.java, teamproject/src/main/java/aihometraining/team/dto/EClassTake.java, teamproject/src/main/java/aihometraining/team/mapper/PaymentMapper.java, teamproject/src/main/java/aihometraining/team/service/PaymentService.java, teamproject/src/main/resources/mapper/PaymentMapper.xml, teamproject/src/main/resources/templates/eClass/eClassTake.html, teamproject/src/main/resources/templates/member/wishList.html, teamproject/src/main/resources/templates/payment/payment.html
[JSG 위시리스트 구현 끝](https://github.com/codeco33/aihometraining/commit/82a542eb9973bd39f52d9c7e8fc813f5ac0dd355)[JSG 수강신청 UI 완성](https://github.com/codeco33/aihometraining/commit/bfe17e483031ee9d9a977245ac3f7fca89d3896
[JSG 수강신청 구현 끝~](https://github.com/codeco33/aihometraining/commit/8ddf859ef26d28755fa0e55e8ee54afaff3636c3)
[JSG 결제페이지 수정](https://github.com/codeco33/aihometraining/commit/603bc5fe53a65c4d4bdb9e7048f3bf5cbb1e98d6)
=> Jsg 위시리스트, 수강신청 구현

teamproject/src/main/java/aihometraining/team/config/WebConfig.java, teamproject/src/main/java/aihometraining/team/controller/MainController.java, teamproject/src/main/java/aihometraining/team/controller/MemberController.java, teamproject/src/main/resources/templates/member/login2.html, teamproject/src/main/resources/templates/member/login3.html, teamproject/src/main/resources/templates/userfragments/header.html, teamproject/src/main/resources/templates/usermain.html
DETAIL : 220415
권한별 로그인 및 메인 화면 작업
=> [LMS] 권한별 로그인 & 메인 화면 작업

teamproject/src/main/resources/templates/fragments/leftmenu.html, teamproject/src/main/resources/templates/userfragments/header.html
DETAIL : 220415
포인트, 위시리스트, 결제 관련 경로 수정 작업
=> [LMS] 포인트, 위시리스트, 결제 관련 경로 수정 작업

teamproject/src/main/java/aihometraining/team/service/MemberService.java
=> [LMS] MemberService 주석 작업

teamproject/src/main/resources/templates/usermain.html
[CBR]메인화면 재수정
Detail: 2022.04.20.00:27
=> [CBR]메인화면 재수정

teamproject/src/main/resources/templates/member/addMember.html, teamproject/src/main/resources/templates/member/login.html
DETAIL: 220420
회원가입, 로그인 js 수정
=> [LMS] 회원가입, 로그인 js 수정

teamproject/src/main/resources/templates/fragments/leftmenu.html
DETAIL : 220421
fragments/leftmenu 운동 클래스 카테고리 관리 경로 작업
=> [LMS] 운동 클래스 카테고리 관리 경로 작업 

teamproject/src/main/java/aihometraining/team/challenge/controller/ChallengeEnterController.java, teamproject/src/main/java/aihometraining/team/challenge/mapper/ChallengeGatherMapper.java, teamproject/src/main/java/aihometraining/team/challenge/service/ChallengeEnterService.java, teamproject/src/main/java/aihometraining/team/controller/MypageController.java, teamproject/src/main/java/aihometraining/team/controller/PaymentController.java, teamproject/src/main/java/aihometraining/team/service/PaymentService.java, teamproject/src/main/resources/mapper/ChallengeEnterMapper.xml, teamproject/src/main/resources/mapper/ChallengeGatherMapper.xml, teamproject/src/main/resources/mapper/PaymentMapper.xml, teamproject/src/main/resources/templates/challenge/challengeGather/challengeGatherList.html, teamproject/src/main/resources/templates/payment/payment.html, teamproject/src/main/resources/templates/payment/paymentDetail.html, teamproject/src/main/resources/templates/userfragments/header.html
=> [JSG] 챌린지 참여 결제 수정

teamproject/src/main/java/aihometraining/team/controller/MypageController.java, teamproject/src/main/java/aihometraining/team/controller/PaymentAdminController.java, teamproject/src/main/resources/templates/payment/mypaymentList.html, teamproject/src/main/resources/templates/payment/paymentList.html
220426 배포 오류로 인한 결제상세내역 페이지 수정
=> [JSG] paymentDetail 관리자 페이지 오류 수정

teamproject/src/main/resources/templates/workoutLog/workoutLogConfig/workoutAIVideoList.html, teamproject/src/main/resources/templates/workoutLog/workoutLogUser/workoutGoalList.html
=> [CMH] 운동 영상 모달 제목 설정

teamproject/pom.xml, teamproject/src/main/resources/templates/diet/dietBankListAdmin.html, teamproject/src/main/resources/templates/diet/updateDietBankList.html, teamproject/src/main/resources/templates/usermain.html
=> [CMH]Maven Build 오류
